# Machine Learning Pipeline

Read --> Split --> divide --> train --> predict --> evaluate

In [39]:
import numpy as np
import pandas as pd

data = {
    "area":[100,150,200,250,300], # the area of the house
    "bedrooms":[2,3,3,4,5], # no. of bedrooms
    "age":[20,15,10,5,2], # age of the house
    "price":[200,300,400,500,650] # the targer (output)
}

df = pd.DataFrame(data)
df.to_csv("housing.csv",index=False)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

# Step 1. Read

In [3]:
df = pd.read_csv("housing.csv")
df.head()

   area  bedrooms  age  price
0   100         2   20    200
1  1550         3   15    300
2   200         3   10    400
3   250         4    5    500
4   300         5    2    650

# Seperate the features and the label

In [9]:
X = df[["area", "bedrooms", "age"]]
y = df["price"]
# we use the X for the learning without using the Y since it's predicting

# Step 3. Split the data

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
# most data needs to be in the learning phase (20% test, 80% train)
# the random state will randomly be splitted in the same way so it's always correct

# Step 4. Train Model
## Step 4.1 : Create the Model
## Step 4.2 : Fit the Model

In [7]:
model = LinearRegression() # creating a model, an object from class linear regression

In [11]:
model.fit(x_train,y_train) # fit the model to my data

LinearRegression()

# Step 5. Predict

In [12]:
y_pred = model.predict(x_test)

# Step 6. Evaluate

In [15]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred)) # since its a regression matrix
print("RMSE: ", rmse)

mse = mean_squared_error(y_test,y_pred)
print("MSE: ", mse)

r2 = r2_score(y_test,y_pred)
print("R2: ", r2)

RMSE:  6300.000000000009
MSE:  39690000.00000011
R2:  nan

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

# ML Pipeline for Linear Regression:

In [17]:
import numpy as np
import pandas as pd

data = {
    "hours_studied":[2,3,4,5,6,7,8,9],
    "attendance":[50,60,70,80,85,90,95,100],
    "passed":[0,0,0,1,1,1,1,1], # the output
}

df = pd.DataFrame(data)
df.to_csv("Students.csv",index=False)

In [19]:
df = pd.read_csv("Students.csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              4          70       0
3              5          80       1
4              6          85       1

In [21]:
X = df[["hours_studied", "attendance"]]
y = df["passed"]

In [23]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [35]:
model.fit(x_train,y_train)

LogisticRegression()

In [36]:
y_pred = model.predict(x_test)

In [37]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

accuracy = accuracy_score(y_test,y_pred)
print("Accuracy: ", accuracy)

precision = precision_score(y_test,y_pred)
print("Precision: ", precision)

recall = recall_score(y_test,y_pred)
print("Recall: ", recall)

f1_score = f1_score(y_test,y_pred)
print("F1 Score: ", f1_score)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0

In [28]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print("RMSE: ", rmse)

mse = mean_squared_error(y_test,y_pred)
print("MSE: ", mse)

r2 = r2_score(y_test,y_pred)
print("R2: ", r2)

RMSE:  0.12548720873684058
MSE:  0.015747039556563397
R2:  0.9370118417737464